import './globals.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous"/>
    <link
      href="https://fonts.googleapis.com/css2?family=Edu+QLD+Beginner:wght@600&family=Poppins:wght@500;700;800&display=swap"
      rel="stylesheet"
    />
      </head>
      <body >{children}</body>
    </html>
  )
}
